### ISSUE TITLE
Crash when using Creative Time machine item

### ISSUE THREAD

**Issue by DatrixTHLK** [rdvdev2/TimeTravelMod#17]
**Describe the bug**
When using the creative time machine item the game crashes to desktop.

**To Reproduce**
1. Open up minecraft
2.  Go to creative mode
3. Find the creative time machine item
4. Take it from the creative menu
5. Right-click the air or ground
6. See error: https://gist.github.com/DatrixTHLK/aab799bdec604260e2ab60a05d479d93

**Expected behavior**
I was hoping to see a different dimension upon using the item. I know the blocks themselves do nothing at this point in time or at least I don't think they do as I tried using them.

**System (please complete the following information):**
 - OS: Windows 10 x64 Home v1803
 - Minecraft Forge Version: 1.12.2-14.23.5.2784
 - Time Travel Mod: 1.12.2-0.1.2.3

**Comment by DatrixTHLK** [comment]
Thanks for the response. I appreciate it

**Comment by rdvdev2** [comment]
@DatrixTHLK were you playing on SinglePlayer or MultiPlayer?

**Comment by rdvdev2** [comment]
I think I got the problem. Try [this build](https://drive.google.com/file/d/1n74OgsLogAJV6_SB9ar9lzWscg1i3xiA/view?usp=sharing) and tell me if it's fixed.

**Comment by rdvdev2** [comment]
I asume it's fixed as my test succeded. If that's not the case please reopen the issue.

**Comment by DatrixTHLK** [comment]
I'm just now getting a look at the github issue tracker. I'll take a look at the update when I get home and see if it is fixed on my end. Thanks for taking a look at the issue and putting out an update.

**Comment by DatrixTHLK** [comment]
It works! thanks very much for fixing the issue. :)
