### ISSUE TITLE
[1.14.4] Sidedness issue running on a dedicated server. renderer/color/BlockColors for invalid dist DEDICATED_SERVER

### ISSUE THREAD

**Issue by ProsperCraft** [rdvdev2/TimeTravelMod#49]
**To Reproduce**
put the mod on a dedicated server.

https://gist.github.com/ProsperCraft/baec1bf665331d59ec3dd1540a0b8bcb

TimeTravelMod-1.14.4-0.1.7.0

**Comment by naritanara** [comment]
Okay, I'm going to solve that now. By the way, don't use 1.14.4-0.1.7.0, it has a bug that makes Time Machines to not work. Use 1.14.4-0.1.7.1 while I solve this.

**Comment by naritanara** [comment]
Will be included in 1.14.4-0.1.7.2
