### ISSUE TITLE
Version checker is off.

### ISSUE THREAD

**Issue by ProsperCraft** [rdvdev2/TimeTravelMod#50]
[net.minecraft.client.gui.NewChatGui/]: [CHAT] A new Time Travel Mod version is available! Check it out in its CourseForge page!

When using TimeTravelMod-1.14.4-0.1.7.1

![7dfa3ac65b6aabb74d99e41e94e44121](https://user-images.githubusercontent.com/4427684/61627607-722c5000-ac3d-11e9-8028-2f76398293d5.png)

**Comment by naritanara** [comment]
Will be included in 1.14.4-0.1.7.2
