### ISSUE TITLE
[1.14.4] Please update to forge .45 so I can add this back to Halk pack.

### ISSUE THREAD

**Issue by ProsperCraft** [rdvdev2/TimeTravelMod#56]
There were breaking changes in Forge .45 please update as it won't load now.

TimeTravelMod-1.14.4-0.1.7.4.jar

**Comment by naritanara** [comment]
Hey! Thanks for adding the mod to your modpack! If all goes well I will publish a new update on August 13th. In that update I will update to forge .45 and solve all the breaking changes. Thanks for reporting!

**Comment by ProsperCraft** [comment]
From the horses mouth - https://mobile.twitter.com/LexManos/status/1158426171500924930?s=09

**Comment by naritanara** [comment]
The fix will be included in 1.14.4-0.1.8.0
