### ISSUE TITLE
[1.15.2] Error Warning in Logfile

### ISSUE THREAD

**Issue by realTIMematrix** [rdvdev2/TimeTravelMod#68]
**Describe the bug**
Receive some error messages in the logfile which can interact with other mods or the vanilla game and produces unwanted effects.

**To Reproduce**
Install Minecraft, Forge 31.0.1 and the mod with game output

**Expected behavior**
Less Warnings in the Logfile

**Suggestions**
1. I recognized that the gunpowder can be used similar to redstone (nice idea). But this interacts possibly with other mods. I would prefer the item "Gunpowderwire" could be crafted with Gunpowder and Strings and not using the same minecraft:gunpowder. There are a lot of spiders and creepers in this huge desert so this should not a problem. 
2. Adding the types to the oldwest biome could avoid best-guessed typoe description. Could be possible that this biome gets some weird description.
3. Here i don't know why this override is needed. Maybe you have an idea to avoid such a message.

**System (please complete the following information):**
 - OS: Windows 10 Pro (64 Bit)
 - Minecraft Forge Version: [1.15.2-31.0.1]
 - Mod Version: [TimeTravelMod-1.15.2-0.2.0.2]

**Mod configuration**
default configuration

**Logfile Messages**

During Startup:

```22:13:47.296 game [22:13:47] [Render thread/INFO] [ne.mi.re.GameData/]: Potentially Dangerous alternative prefix `minecraft` for name `gunpowder`, expected `timetravelmod`. This could be a intended override, but in most cases indicates a broken mod.```

`22:13:49.612 game [22:13:49] [modloading-worker-10/WARN] [ne.mi.co.BiomeDictionary/]: No types have been added to Biome timetravelmod:oldwest, types have been assigned on a best-effort guess: [DRY, HOT, DESERT]`

Messages after creating a new game:

```22:24:42.926 game [22:24:42] [Server thread/INFO] [ne.mi.re.GameData/]: Potentially Dangerous alternative prefix `timetravelmod` for name `oldwest_layered`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.```

**BTW:** 
I really, really like this mod and hope there will be more TimeTravel Biomes with specific music. For example a wild, huge jungle with maja pyramides or something similar to greek or egypt culture.

**Comment by naritanara** [comment]
I'm out of time for today, but I will address this tomorrow. I feel 1 and 2 will be an easy fix, as they're my fault for not doing things well (these features are based in relatively old mc version and code). Third one seems a little but tough as it seems like mc thinks that my biome generator is vanilla, so no clue what went wrong there. Anyway, these warnings shouldn't be interfering with other mods, unless they also modify vanilla gunpowder, which is very unlikely.

Regarding the biomes request, the next biome (which I will start working soon) will be future themed, but I will add your idea to the mod plans.

Thanks for the feedback!

**Comment by naritanara** [comment]
Fixing progress:
- [x] Gunpowder warnings
- [x] BiomeDictionary warnings
- [x] BiomeProviderType warnings

**Comment by naritanara** [comment]
I just merged the fixed code into the main branch. All the warnings will disappear on the next update.
