### ISSUE TITLE
[1.12.2] Mod crashes at start with other dimension mods! Failed to register dimension for id 20, One is already registered

### ISSUE THREAD

**Issue by ImMineOfficial** [rdvdev2/TimeTravelMod#78]
**Describe the bug**
When I installed the mod then crashes Minecraft at the beginning of the second phase of Forge.

**To Reproduce**
1. Install the mod in the Twitch Launcher.
2. Start the game.
3. And then crashes the game.
4. See error!

**Expected behavior**
I've expected that the mod works.

**Screenshots**

**System (please complete the following information):**
 - OS: Windows 10
 - Minecraft Forge Version: forge-1.12.2-14.23.5.2847
 - Mod Version: the newest for the 1.12.2 version.

**Mod configuration**
Its the standard configuration.

**Additional context**
I think its maybe because their are other dimension mods. The Betweenlands, The Erebus and Atum 2 is installed. And Dimensionaldoors before I've had also WayThroughDimensions installed but I removed it and their are still crashes.

Here is the crashlog: https://paste.labymod.net/umecilolav.sql

**Comment by naritanara** [comment]
1.12.2 is unsupported both by me and the Forge Team. Update to 1.15.2.

**Comment by ImMineOfficial** [comment]
Wow. Very nice support...
